---
title: "GMLNET"
author: "Samb"
date: "15 avril 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(magrittr)
library(text2vec)
library(tokenizers)
library(glmnet)
library(doParallel)
registerDoParallel(4)
```

### Chargement des données
```{r}
train <- read_csv("C:/Users/morsa/Documents/Notebook/TP_Toxic_comment/Data/train_preprocessed.csv") 
test <- read_csv("C:/Users/morsa/Documents/Notebook/TP_Toxic_comment/Data/test_preprocessed.csv") 
subm <- read_csv("C:/Users/morsa/Documents/Notebook/TP_Toxic_comment/Data/sample_submission.csv") 

```

```{r}
tri <- 1:nrow(train)
targets <- c("toxic", "severe_toxic", "obscene", "threat", "insult", "identity_hate")

```

```{r}
#---------------------------
cat("Basic preprocessing & stats...\n")
tr_te <- train %>% 
  select(-one_of(targets)) %>% 
  bind_rows(test) %>% 
  mutate(length = str_length(comment_text),
         ncap = str_count(comment_text, "[A-Z]"),
         ncap_len = ncap / length,
         nexcl = str_count(comment_text, fixed("!")),
         nquest = str_count(comment_text, fixed("?")),
         npunct = str_count(comment_text, "[[:punct:]]"),
         nword = str_count(comment_text, "\\w+"),
         nsymb = str_count(comment_text, "&|@|#|\\$|%|\\*|\\^"),
         nsmile = str_count(comment_text, "((?::|;|=)(?:-)?(?:\\)|D|P))")) %>% 
  select(-id) %T>% 
  glimpse()

```

```{r}
#---------------------------
cat("Parsing comments...\n")
it <- tr_te %$%
  str_to_lower(comment_text) %>%
  str_replace_all("[^[:alpha:]]", " ") %>%
  str_replace_all("\\s+", " ") %>%
  itoken(tokenizer = tokenize_word_stems)

vectorizer <- create_vocabulary(it, ngram = c(1, 1), stopwords = stopwords("en")) %>%
  prune_vocabulary(term_count_min = 3, doc_proportion_max = 0.5, vocab_term_max = 4000) %>%
  vocab_vectorizer()


m_tfidf <- TfIdf$new(norm = "l2", sublinear_tf = T)
tfidf <- create_dtm(it, vectorizer) %>%
  fit_transform(m_tfidf)  

m_lsa <- LSA$new(n_topics = 25, method = "randomized")
lsa <- fit_transform(tfidf, m_lsa)

```

```{r}
#---------------------------
cat("Preparing data for glmnet...\n")
X <- tr_te %>% 
  select(-comment_text) %>% 
  sparse.model.matrix(~ . - 1, .) %>% 
  cbind(tfidf, lsa)

X_test <- X[-tri, ]
X <- X[tri, ]

rm(tr_te, test, tri, it, vectorizer, dtm, m_lsa, lsa); gc()

```

```{r}
#---------------------------
cat("Training glmnet & predicting...\n")
for (target in targets) {
  cat("\nFitting", target, "...\n")
  y <- factor(train[[target]])
  m_glm <- cv.glmnet(X, y, alpha = 0, family = "binomial", type.measure = "auc",
                     parallel = T, standardize = T, nfolds = 4, nlambda = 100)
  cat("\tAUC:", max(m_glm$cvm))
  subm[[target]] <- predict(m_glm, X_test, type = "response", s = "lambda.min")
}
```


```{r}
cat("Creating submission file...\n")
write_csv(subm, "tidy_glm.csv")

```

